apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

namePrefix: rc-

bases:
  - ../../base

commonLabels:
  environment: rc

replicas:
  - name: ciyex-app
    count: 1

images:
  - name: IMAGE_URL
    newName: IMAGE_URL
    newTag: IMAGE_TAG

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
