--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Debian 16.9-1.pgdg110+1)
-- Dumped by pg_dump version 16.9 (Debian 16.9-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--

CREATE SCHEMA IF NOT EXISTS public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;


-- flyway_schema_history is managed by Flyway itself and should not be created by migration scripts.

--
-- Name: orgs; Type: TABLE; Schema: public; Owner: postgres
--

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'orgs'
    ) THEN
        CREATE TABLE public.orgs (
            id bigint NOT NULL,
            address character varying(255),
            city character varying(255),
            country character varying(255),
            fhir_id character varying(255),
            org_name character varying(255) NOT NULL,
            postal_code character varying(255),
            state character varying(255),
            status character varying(16) NOT NULL DEFAULT 'ACTIVE'
        );
        ALTER TABLE public.orgs OWNER TO postgres;
    END IF;
END
$$;

-- Create identity sequence for orgs.id only if it isn't already an identity column
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'orgs' AND column_name = 'id' AND is_identity = 'YES'
    ) THEN
        ALTER TABLE public.orgs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.orgs_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;
END
$$;


--
-- Name: user_org_roles; Type: TABLE; Schema: public; Owner: postgres
--

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'user_org_roles'
    ) THEN
        CREATE TABLE public.user_org_roles (
            id bigint NOT NULL,
            role character varying(20) NOT NULL,
            org_id bigint NOT NULL,
            user_id bigint NOT NULL,
            CONSTRAINT user_org_roles_role_check CHECK (((role)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'ADMIN'::character varying, 'PROVIDER'::character varying, 'PATIENT'::character varying, 'NURSE'::character varying, 'RECEPTIONIST'::character varying, 'BILLER'::character varying, 'STAFF'::character varying])::text[])))
        );
        ALTER TABLE public.user_org_roles OWNER TO postgres;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'user_org_roles' AND column_name = 'id' AND is_identity = 'YES'
    ) THEN
        ALTER TABLE public.user_org_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.user_org_roles_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;
END
$$;


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'users'
    ) THEN
        CREATE TABLE public.users (
            id bigint NOT NULL,
            city character varying(255),
            country character varying(255),
            date_of_birth date,
            email character varying(255) NOT NULL,
            first_name character varying(255),
            last_name character varying(255),
            middle_name character varying(255),
            password character varying(255) NOT NULL,
            phone_number character varying(255),
            postal_code character varying(255),
            profile_image character varying(255),
            security_answer character varying(255),
            security_question character varying(255),
            state character varying(255),
            street character varying(255),
            street2 character varying(255),
            uuid uuid
        );
        ALTER TABLE public.users OWNER TO postgres;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'id' AND is_identity = 'YES'
    ) THEN
        ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.users_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;
END
$$;




-- Primary key for flyway_schema_history is managed by Flyway.


DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'orgs_pkey') THEN
        ALTER TABLE ONLY public.orgs
            ADD CONSTRAINT orgs_pkey PRIMARY KEY (id);
    END IF;
END
$$;


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk6dotkott2kjsp8vw4d0m25fb7') THEN
        ALTER TABLE ONLY public.users
            ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);
    END IF;
END
$$;


--
-- Name: orgs ukl72x9w0lb26ikpybtt5niys03; Type: CONSTRAINT; Schema: public; Owner: postgres
--

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ukl72x9w0lb26ikpybtt5niys03') THEN
        ALTER TABLE ONLY public.orgs
            ADD CONSTRAINT ukl72x9w0lb26ikpybtt5niys03 UNIQUE (org_name);
    END IF;
END
$$;


--
-- Name: user_org_roles user_org_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_org_roles_pkey') THEN
        ALTER TABLE ONLY public.user_org_roles
            ADD CONSTRAINT user_org_roles_pkey PRIMARY KEY (id);
    END IF;
END
$$;


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_pkey') THEN
        ALTER TABLE ONLY public.users
            ADD CONSTRAINT users_pkey PRIMARY KEY (id);
    END IF;
END
$$;


--
-- Name: admin_templates; Type: TABLE; Schema: public; Owner: postgres
--

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'admin_templates'
    ) THEN
        CREATE TABLE public.admin_templates (
            id bigint NOT NULL,
            locations character varying(255) NOT NULL,
            practice_type character varying(255) NOT NULL,
            created_at timestamp without time zone NOT NULL,
            updated_at timestamp without time zone
        );
        ALTER TABLE public.admin_templates OWNER TO postgres;
    END IF;
END
$$;

-- Create identity sequence for admin_templates.id only if it isn't already an identity column
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'admin_templates' AND column_name = 'id' AND is_identity = 'YES'
    ) THEN
        ALTER TABLE public.admin_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.admin_templates_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;
END
$$;

-- Primary key for admin_templates
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'admin_templates_pkey') THEN
        ALTER TABLE ONLY public.admin_templates
            ADD CONSTRAINT admin_templates_pkey PRIMARY KEY (id);
    END IF;
END
$$;

-- Foreign key to orgs
-- (removed fk_admin_templates_org_id since admin_templates no longer contains org_id)



-- Index for flyway_schema_history is managed by Flyway.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk60fafnm5wk9bx6snghwir4w3f') THEN
        ALTER TABLE ONLY public.user_org_roles
            ADD CONSTRAINT fk60fafnm5wk9bx6snghwir4w3f FOREIGN KEY (user_id) REFERENCES public.users(id);
    END IF;
END
$$;


--
-- Name: user_org_roles fk9leq3m0w54f0ryocaiq4cu2ec; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk9leq3m0w54f0ryocaiq4cu2ec') THEN
        ALTER TABLE ONLY public.user_org_roles
            ADD CONSTRAINT fk9leq3m0w54f0ryocaiq4cu2ec FOREIGN KEY (org_id) REFERENCES public.orgs(id);
    END IF;
END
$$;


--
-- PostgreSQL database dump complete
--

