apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  labels:
    jenkins: agent
spec:
  containers:
    - name: jnlp
      image: <registry>/ciyex-jenkins-agent:<tag>
      imagePullPolicy: IfNotPresent
      args:
        - ${computer.jnlpmac}
        - ${computer.name}
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
  restartPolicy: Never
