// main_website/app/layout.tsx
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import ClientThemeWrapper from "./ClientThemeWrapper";
import { CartProvider } from "@/components/context/CartContext";
import { TestOrderProvider } from "@/components/context/TestOrderContext";
import { ToasterProvider } from "./components/ToasterProvider";
import GoogleTagManager from "./components/GoogleTagManager";
import GoogleAnalytics from "./components/GoogleAnalytics";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "OurTopClinic",
    description: "Generated by create next app",
    icons: {
        icon: [
            { url: '/logo1.png', sizes: '32x32', type: 'image/png' },
            { url: '/logo1.png', sizes: '16x16', type: 'image/png' }
        ],
        shortcut: '/logo1.png',
        apple: '/logo1.png',
    },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta httpEquiv="Permissions-Policy" content="publickey-credentials-get=*" />
            <link rel="icon" href="/logo.png" type="image/png" />
            <GoogleTagManager />
            <GoogleAnalytics />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
        <noscript>
            <iframe
                src={`https://www.googletagmanager.com/ns.html?id=${process.env.NEXT_PUBLIC_GTM_ID}`}
                height="0"
                width="0"
                style={{ display: 'none', visibility: 'hidden' }}
            />
        </noscript>
        <Providers>
            <CartProvider>
                <TestOrderProvider>
                    <ClientThemeWrapper>
                        {children}
                    </ClientThemeWrapper>
                </TestOrderProvider>
            </CartProvider>
        </Providers>
        <ToasterProvider />
        <Analytics />
        </body>
        </html>
    );
}
