-- AlterTable
ALTER TABLE "Patient" ADD COLUMN     "banner_image" TEXT,
ADD COLUMN     "profile_image" TEXT,
ALTER COLUMN "height" DROP NOT NULL,
ALTER COLUMN "weight" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "emergency_contact_name" DROP NOT NULL,
ALTER COLUMN "emergency_contact_number" DROP NOT NULL,
ALTER COLUMN "relation" DROP NOT NULL,
ALTER COLUMN "privacy_consent" SET DEFAULT true,
ALTER COLUMN "service_consent" SET DEFAULT true,
ALTER COLUMN "medical_consent" SET DEFAULT true,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "state" DROP NOT NULL,
ALTER COLUMN "zip_code" DROP NOT NULL,
ALTER COLUMN "preferred_appointment_type" DROP NOT NULL,
ALTER COLUMN "preferred_contact_method" DROP NOT NULL,
ALTER COLUMN "marital_status" DROP NOT NULL,
ALTER COLUMN "marital_status" SET DEFAULT 'SINGLE';
