create table portal_pending_updates
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    approved_by        varchar(255),
    approver_notes     varchar(1000),
    hint               varchar(500),
    patient_notes      varchar(1000),
    payload            jsonb,
    priority           varchar(20),
    rejection_reason   varchar(500),
    reviewed_date      timestamp(6),
    status             varchar(20)  not null,
    update_type        varchar(50)  not null,
    user_id            bigint       not null
);

alter table portal_pending_updates
    owner to postgres;

create table allergy_intolerances
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    allergy_name       varchar(255),
    comments           varchar(255),
    end_date           varchar(255),
    external_id        varchar(255),
    patient_id         bigint       not null,
    reaction           varchar(255),
    severity           varchar(255),
    start_date         varchar(255),
    status             varchar(255)
);

alter table allergy_intolerances
    owner to postgres;

create table allergy_details
(
    id                     bigint generated by default as identity
        primary key,
    created_by             varchar(100),
    created_date           timestamp(6) not null,
    last_modified_by       varchar(100),
    last_modified_date     timestamp(6) not null,
    tenant_name            varchar(100) not null,
    allergy_name           varchar(255),
    reaction               varchar(255),
    severity               varchar(255),
    status                 varchar(255),
    allergy_intolerance_id bigint       not null
        constraint fkh624duw8w9u0nglqxlv4w6srp
            references allergy_intolerances
);

alter table allergy_details
    owner to postgres;

create table appointments
(
    id                     bigint generated by default as identity
        primary key,
    created_by             varchar(100),
    created_date           timestamp(6) not null,
    last_modified_by       varchar(100),
    last_modified_date     timestamp(6) not null,
    tenant_name            varchar(100) not null,
    appointment_end_date   varchar(255),
    appointment_end_time   varchar(255),
    appointment_start_date varchar(255),
    appointment_start_time varchar(255),
    location_id            bigint,
    patient_id             bigint       not null,
    priority               varchar(255),
    provider_id            bigint       not null,
    reason                 varchar(2000),
    status                 varchar(255),
    visit_type             varchar(255) not null
);

alter table appointments
    owner to postgres;

create table assessment
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    assessment_text    text,
    diagnosis_code     varchar(64),
    diagnosis_name     varchar(512),
    e_signed           boolean,
    encounter_id       bigint       not null,
    external_id        varchar(128),
    notes              text,
    patient_id         bigint       not null,
    printed_at         timestamp(6) with time zone,
    priority           varchar(64),
    signed_at          timestamp(6) with time zone,
    signed_by          varchar(128),
    status             varchar(64)
);

alter table assessment
    owner to postgres;

create table assigned_providers
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    e_signed           boolean,
    encounter_id       bigint       not null,
    end_date           varchar(16),
    external_id        varchar(255),
    notes              text,
    patient_id         bigint       not null,
    printed_at         timestamp(6) with time zone,
    provider_id        bigint       not null,
    role               varchar(32)  not null,
    signed_at          timestamp(6) with time zone,
    signed_by          varchar(128),
    start_date         varchar(16),
    status             varchar(24)
);

alter table assigned_providers
    owner to postgres;

create table billing_autopay
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    cardid             bigint,
    enabled            boolean,
    frequency          varchar(255),
    maxamount          double precision,
    startdate          date,
    userid             bigint
);

alter table billing_autopay
    owner to postgres;

create table chief_complaint
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    complaint          varchar(255),
    details            varchar(255),
    e_signed           boolean,
    encounter_id       bigint,
    patient_id         bigint,
    printed_at         timestamp(6) with time zone,
    severity           varchar(255),
    signed_at          timestamp(6) with time zone,
    signed_by          varchar(128),
    status             varchar(255)
);

alter table chief_complaint
    owner to postgres;

create table code_types
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    active             boolean,
    claim_flag         boolean,
    code_type_id       integer,
    code_type_key      varchar(64)  not null,
    diagnosis_flag     boolean,
    drug_flag          boolean,
    encounter_id       bigint       not null,
    external_flag      boolean,
    external_id        varchar(255),
    fee_applicable     boolean,
    justification      varchar(128),
    label              varchar(256),
    mask               varchar(128),
    modifier           integer,
    number_of_services boolean,
    patient_id         bigint       not null,
    problem_flag       boolean,
    procedure_flag     boolean,
    related_indicator  boolean,
    sequence_number    integer,
    terminology_flag   boolean
);

alter table code_types
    owner to postgres;

create index idx_codetypes_key
    on code_types (code_type_key, code_type_id);

create table codes
(
    id                  bigint generated by default as identity
        primary key,
    created_by          varchar(100),
    created_date        timestamp(6) not null,
    last_modified_by    varchar(100),
    last_modified_date  timestamp(6) not null,
    tenant_name         varchar(100) not null,
    active              boolean,
    category            varchar(64),
    code                varchar(32)  not null,
    code_type           varchar(16)  not null,
    description         text,
    diagnosis_reporting boolean,
    e_signed            boolean,
    encounter_id        bigint       not null,
    external_id         varchar(255),
    fee_standard        numeric(18, 2),
    modifier            varchar(16),
    patient_id          bigint       not null,
    printed_at          timestamp(6) with time zone,
    relate_to           varchar(128),
    service_reporting   boolean,
    short_description   varchar(256),
    signed_at           timestamp(6) with time zone,
    signed_by           varchar(128)
);

alter table codes
    owner to postgres;

create index idx_codes_type_code
    on codes (code_type, code);

create table communications
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    category           varchar(255),
    external_id        varchar(255),
    in_response_to     varchar(255),
    patient_id         bigint,
    payload            text,
    provider_id        bigint,
    recipients         varchar(255),
    sender             varchar(255),
    sent_date          varchar(255),
    status             varchar(255)
        constraint communications_status_check
            check ((status)::text = ANY
        ((ARRAY ['COMPLETED'::character varying, 'IN_PROGRESS'::character varying, 'ENTERED_IN_ERROR'::character varying, 'SENT'::character varying, 'RECEIVED'::character varying, 'ARCHIVED'::character varying])::text[])),
    subject            varchar(255)
);

alter table communications
    owner to postgres;

create table date_time_finalized
(
    id                    bigint generated by default as identity
        primary key,
    created_by            varchar(100),
    created_date          timestamp(6) not null,
    last_modified_by      varchar(100),
    last_modified_date    timestamp(6) not null,
    tenant_name           varchar(100) not null,
    comments              text,
    content_hash          varchar(128),
    e_signed              boolean,
    encounter_id          bigint       not null,
    external_id           varchar(255),
    finalized_at          varchar(40)  not null,
    finalized_by          varchar(128),
    finalizer_role        varchar(64),
    method                varchar(16),
    patient_id            bigint       not null,
    printed_at            timestamp(6) with time zone,
    provider_signature_id bigint,
    reason                varchar(256),
    signed_at             timestamp(6) with time zone,
    signed_by             varchar(128),
    signoff_id            bigint,
    status                varchar(24),
    target_id             bigint,
    target_type           varchar(32),
    target_version        varchar(64)
);

alter table date_time_finalized
    owner to postgres;

create table document
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    category           varchar(255),
    contenttype        varchar(255),
    description        varchar(255),
    encryptionkey      varchar(512),
    fhirexternalid     varchar(255),
    filename           varchar(255),
    iv                 varchar(255),
    patientid          bigint,
    s3bucket           varchar(255),
    s3key              varchar(255),
    type               varchar(255)
);

alter table document
    owner to postgres;

create table document_settings
(
    id                      integer generated by default as identity
        primary key,
    created_by              varchar(100),
    created_date            timestamp(6) not null,
    last_modified_by        varchar(100),
    last_modified_date      timestamp(6) not null,
    tenant_name             varchar(100) not null,
    allowed_file_types_json text         not null,
    categories_json         text         not null,
    enable_audio            boolean      not null,
    encryption_enabled      boolean      not null,
    max_upload_bytes        bigint       not null,
    updatedat               timestamp(6) with time zone,
    updatedby               varchar(255)
);

alter table document_settings
    owner to postgres;

create table enc_fee_schedules
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    currency           varchar(8),
    effective_from     varchar(16),
    effective_to       varchar(16),
    encounter_id       bigint       not null,
    external_id        varchar(255),
    name               varchar(128) not null,
    notes              text,
    patient_id         bigint       not null,
    payer              varchar(128),
    status             varchar(24)
);

alter table enc_fee_schedules
    owner to postgres;

create table enc_fee_schedule_entries
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    active             boolean,
    amount             numeric(18, 2),
    code               varchar(32)  not null,
    code_type          varchar(16)  not null,
    currency           varchar(8),
    description        text,
    modifier           varchar(16),
    notes              text,
    unit               varchar(32),
    schedule_id        bigint       not null
        constraint fk3qs7yb9qtswey5ia9yk4e6kog
            references enc_fee_schedules
);

alter table enc_fee_schedule_entries
    owner to postgres;

create index idx_efse_sched
    on enc_fee_schedule_entries (schedule_id);

create index idx_efse_code
    on enc_fee_schedule_entries (code_type, code, modifier);

create table encounter
(
    id                   bigint generated by default as identity
        primary key,
    created_by           varchar(100),
    created_date         timestamp(6) not null,
    last_modified_by     varchar(100),
    last_modified_date   timestamp(6) not null,
    tenant_name          varchar(100) not null,
    dischargedisposition varchar(255),
    encounter_date       timestamp(6),
    encounterprovider    varchar(255),
    incollection         boolean,
    patientid            bigint       not null,
    reasonforvisit       varchar(255),
    sensitivity          varchar(255),
    status               varchar(255)
        constraint encounter_status_check
            check ((status)::text = ANY
        ((ARRAY ['UNSIGNED'::character varying, 'SIGNED'::character varying, 'INCOMPLETE'::character varying])::text[])),
    type                 varchar(255),
    visitcategory        varchar(255)
);

alter table encounter
    owner to postgres;

create table family_history
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    e_signed           boolean,
    encounter_id       bigint       not null,
    external_id        varchar(255),
    patient_id         bigint       not null,
    printed_at         timestamp(6) with time zone,
    signed_at          timestamp(6) with time zone,
    signed_by          varchar(128),
    signed_entry_id    bigint
);

alter table family_history
    owner to postgres;

create table family_history_entry
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    diagnosis_code     varchar(64),
    diagnosis_text     varchar(255),
    notes              varchar(1000),
    relation           varchar(24)  not null,
    family_history_id  bigint       not null
        constraint fkio46fqpdi3vnukh5jxptwxyo4
            references family_history
);

alter table family_history_entry
    owner to postgres;

create table gps_billing_cards
(
    id                    bigint generated by default as identity
        primary key,
    created_by            varchar(100),
    created_date          timestamp(6) not null,
    last_modified_by      varchar(100),
    last_modified_date    timestamp(6) not null,
    tenant_name           varchar(100) not null,
    address               varchar(255),
    brand                 varchar(20),
    city                  varchar(100),
    exp_month             integer,
    exp_year              integer,
    first_name            varchar(100),
    gps_customer_vault_id varchar(64),
    is_default            boolean,
    last4                 varchar(4),
    last_name             varchar(100),
    state                 varchar(50),
    street                varchar(255),
    user_id               bigint       not null,
    zip                   varchar(20)
);

alter table gps_billing_cards
    owner to postgres;

create table healthcareservice
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    description        varchar(255),
    hoursofoperation   varchar(255),
    location           varchar(255),
    name               varchar(255),
    type               varchar(255)
);

alter table healthcareservice
    owner to postgres;

create table history_of_present_illness
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    description        text,
    e_signed           boolean,
    encounter_id       bigint       not null,
    external_id        varchar(255),
    patient_id         bigint       not null,
    printed_at         timestamp(6) with time zone,
    signed_at          timestamp(6) with time zone,
    signed_by          varchar(128)
);

alter table history_of_present_illness
    owner to postgres;

create table immunizations
(
    id                     bigint generated by default as identity
        primary key,
    created_by             varchar(100),
    created_date           timestamp(6) not null,
    last_modified_by       varchar(100),
    last_modified_date     timestamp(6) not null,
    tenant_name            varchar(100) not null,
    administrationsite     varchar(255),
    administratorname      varchar(255),
    administratortitle     varchar(255),
    amountadministered     varchar(255),
    completionstatus       varchar(255),
    cvxcode                varchar(255),
    datetimeadministered   varchar(255),
    datevisgiven           varchar(255),
    datevisstatement       varchar(255),
    expirationdate         varchar(255),
    external_id            varchar(255),
    informationsource      varchar(255),
    lotnumber              varchar(255),
    manufacturer           varchar(255),
    notes                  varchar(255),
    orderingprovider       varchar(255),
    patient_id             bigint       not null,
    reasoncode             varchar(255),
    route                  varchar(255),
    substancerefusalreason varchar(255)
);

alter table immunizations
    owner to postgres;

create table insurance_companies
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    address            varchar(255),
    city               varchar(255),
    country            varchar(255),
    fhir_id            varchar(255),
    name               varchar(255) not null,
    payer_id           varchar(255),
    postal_code        varchar(255),
    state              varchar(255),
    status             varchar(255) not null
        constraint insurance_companies_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'ARCHIVED'::character varying])::text[]))
    );

alter table insurance_companies
    owner to postgres;

create table coverages
(
    id                       bigint generated by default as identity
        primary key,
    created_by               varchar(100),
    created_date             timestamp(6) not null,
    last_modified_by         varchar(100),
    last_modified_date       timestamp(6) not null,
    tenant_name              varchar(100) not null,
    byholder_address_line1   varchar(255),
    byholder_address_line2   varchar(255),
    byholder_city            varchar(255),
    byholder_country         varchar(255),
    byholder_name            varchar(255),
    byholder_phone           varchar(255),
    byholder_relation        varchar(255),
    byholder_state           varchar(255),
    byholder_zip_code        varchar(255),
    copay_amount             double precision,
    coverage_end_date        varchar(255),
    coverage_start_date      varchar(255),
    coverage_type            varchar(255),
    effective_date           varchar(255),
    effective_date_end       varchar(255),
    external_id              varchar(255),
    group_number             varchar(255),
    patient_id               bigint,
    plan_name                varchar(255),
    policy_number            varchar(255),
    provider                 varchar(255),
    subscriber_address_line1 varchar(255),
    subscriber_address_line2 varchar(255),
    subscriber_city          varchar(255),
    subscriber_country       varchar(255),
    subscriber_employer      varchar(255),
    subscriber_phone         varchar(255),
    subscriber_state         varchar(255),
    subscriber_zip_code      varchar(255),
    insurance_company_id     bigint
        constraint fk7ena3iyxg1qylpd0kn2e3wkrl
            references insurance_companies
);

alter table coverages
    owner to postgres;

create table inventory
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    category           varchar(255),
    expiry             varchar(255),
    externalid         varchar(255),
    location           varchar(255),
    lot                varchar(255),
    minstock           integer,
    name               varchar(255),
    sku                varchar(255),
    status             varchar(255),
    stock              integer,
    supplier           varchar(255),
    unit               varchar(255)
);

alter table inventory
    owner to postgres;

create table inventorysettings
(
    id                     bigint generated by default as identity
        primary key,
    created_by             varchar(100),
    created_date           timestamp(6) not null,
    last_modified_by       varchar(100),
    last_modified_date     timestamp(6) not null,
    tenant_name            varchar(100) not null,
    autoreordersuggestions boolean      not null,
    criticallowpercentage  integer      not null,
    lowstockalerts         boolean      not null
);

alter table inventorysettings
    owner to postgres;

create table invoice
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    currency           varchar(255),
    due_date           varchar(255),
    encounter_id       bigint       not null,
    external_id        varchar(255),
    invoice_number     varchar(255),
    issue_date         varchar(255),
    notes              text,
    org_id             bigint       not null,
    patient_id         bigint       not null,
    payer              varchar(255),
    status             varchar(255),
    total_gross        numeric(18, 2),
    total_net          numeric(18, 2)
);

alter table invoice
    owner to postgres;

create table invoice_bills
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6)   not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6)   not null,
    tenant_name        varchar(100)   not null,
    amount             numeric(12, 2) not null,
    due_date           timestamp(6),
    external_id        varchar(255),
    invoice_number     varchar(255),
    invoice_url        varchar(255),
    paid_at            timestamp(6),
    receipt_url        varchar(255),
    status             varchar(255)
        constraint invoice_bills_status_check
            check ((status)::text = ANY
        ((ARRAY ['UNPAID'::character varying, 'PENDING'::character varying, 'PAID'::character varying, 'CANCELLED'::character varying, 'ARCHIVED'::character varying])::text[])),
    subscription_id    bigint,
    user_id            bigint
);

alter table invoice_bills
    owner to postgres;

create table billing_history
(
    id                       bigint generated by default as identity
        primary key,
    created_by               varchar(100),
    created_date             timestamp(6)   not null,
    last_modified_by         varchar(100),
    last_modified_date       timestamp(6)   not null,
    tenant_name              varchar(100)   not null,
    amount                   numeric(10, 2) not null,
    gps_customer_vault_id    varchar(64),
    gps_transaction_id       varchar(64),
    invoice_url              varchar(255),
    provider                 varchar(20)    not null
        constraint billing_history_provider_check
            check ((provider)::text = ANY
        ((ARRAY ['STRIPE'::character varying, 'GPS'::character varying, 'INVOICE'::character varying])::text[])),
    receipt_url              varchar(255),
    response_code            integer,
    response_message         varchar(500),
    status                   varchar(20)    not null
        constraint billing_history_status_check
            check ((status)::text = ANY
                   ((ARRAY ['SUCCEEDED'::character varying, 'FAILED'::character varying, 'PENDING'::character varying, 'PROCESSING'::character varying, 'CANCELED'::character varying, 'ARCHIVED'::character varying, 'DECLINED'::character varying])::text[])),
    stripe_payment_intent_id varchar(255),
    stripe_payment_method_id varchar(255),
    user_id                  bigint         not null,
    invoice_bill_id          bigint
        constraint fkg5u7u6wme1fmtvovvp5nn6aq8
            references invoice_bills
);

alter table billing_history
    owner to postgres;

create table invoice_line
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    amount             numeric(18, 2),
    code               varchar(20),
    description        varchar(1024),
    quantity           integer,
    unit_price         numeric(18, 2),
    invoice_id         bigint       not null
        constraint fkfnwks1ouvwbttl0fklxsem7ik
            references invoice
);

alter table invoice_line
    owner to postgres;

create table invoice_payment
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    amount             numeric(18, 2),
    pay_date           varchar(255),
    method             varchar(32),
    note               text,
    reference          varchar(64),
    invoice_id         bigint       not null
        constraint fkkopeu965ps1ljahtib8n8nub2
            references invoice
);

alter table invoice_payment
    owner to postgres;

create table lab_orders
(
    id                  bigint generated by default as identity
        primary key,
    created_by          varchar(100),
    created_date        timestamp(6) not null,
    last_modified_by    varchar(100),
    last_modified_date  timestamp(6) not null,
    tenant_name         varchar(100) not null,
    encounter_id        varchar(255),
    icd_id              varchar(64),
    lab_name            varchar(255),
    mrn                 varchar(255),
    notes               varchar(2048),
    order_date          varchar(255),
    order_datetime      varchar(255),
    order_name          varchar(255),
    order_number        varchar(255),
    ordering_provider   varchar(255),
    patient_external_id varchar(255),
    patient_first_name  varchar(255),
    patient_home_phone  varchar(255),
    patient_id          bigint,
    patient_last_name   varchar(255),
    physician_name      varchar(255),
    priority            varchar(255),
    result              varchar(4096),
    specimen_id         varchar(255),
    status              varchar(255),
    test_code           varchar(255),
    test_display        varchar(255)
);

alter table lab_orders
    owner to postgres;

create table list_options
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    activity           integer,
    codes              varchar(255),
    edit_options       boolean      not null,
    is_default         boolean      not null,
    last_updated       timestamp(6),
    list_id            varchar(255) not null,
    notes              varchar(255),
    option_id          varchar(255) not null,
    option_value       real,
    orgid              varchar(255),
    seq                integer      not null,
    timestamp          timestamp(6) not null,
    title              varchar(255) not null
);

alter table list_options
    owner to postgres;

create table locations
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    address            varchar(255),
    city               varchar(255),
    country            varchar(255),
    external_id        varchar(255),
    name               varchar(255),
    postalcode         varchar(255),
    state              varchar(255)
);

alter table locations
    owner to postgres;

create table maintenance
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    assignee           varchar(255),
    category           varchar(255),
    duedate            varchar(255),
    equipment          varchar(255),
    externalid         varchar(255),
    lastservicedate    varchar(255),
    location           varchar(255),
    notes              varchar(2000),
    priority           varchar(255),
    status             varchar(255),
    vendor             varchar(255)
);

alter table maintenance
    owner to postgres;

create table medical_problems
(
    id                  bigint generated by default as identity
        primary key,
    created_by          varchar(100),
    created_date        timestamp(6) not null,
    last_modified_by    varchar(100),
    last_modified_date  timestamp(6) not null,
    tenant_name         varchar(100) not null,
    external_id         varchar(255),
    note                varchar(2000),
    occurrence          varchar(255),
    outcome             varchar(255),
    patient_id          bigint       not null,
    title               varchar(255),
    verification_status varchar(255)
);

alter table medical_problems
    owner to postgres;

create table medication_requests
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    date_issued        varchar(255),
    dosage             varchar(255),
    encounter_id       bigint,
    instructions       varchar(255),
    medication_name    varchar(255),
    patient_id         bigint,
    prescribing_doctor varchar(255),
    status             varchar(255)
);

alter table medication_requests
    owner to postgres;

create table orders
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    amount             double precision,
    category           varchar(255),
    date               varchar(255),
    externalid         varchar(255),
    itemname           varchar(255),
    ordernumber        varchar(255),
    status             varchar(255),
    stock              integer,
    supplier           varchar(255),
    inventory_id       bigint
        constraint fkn6v1kjethk891xl3ow3a17qf7
            references inventory
);

alter table orders
    owner to postgres;

create table past_medical_history
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    description        text,
    e_signed           boolean,
    encounter_id       bigint       not null,
    external_id        varchar(255),
    patient_id         bigint       not null,
    printed_at         timestamp(6) with time zone,
    signed_at          timestamp(6) with time zone,
    signed_by          varchar(128)
);

alter table past_medical_history
    owner to postgres;

create table patient_account_credit
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    balance            numeric(12, 2),
    orgid              bigint       not null,
    patientid          bigint       not null,
    constraint uk_credit_patient
        unique (orgid, patientid)
);

alter table patient_account_credit
    owner to postgres;

create table patient_billing_notes
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    invoiceid          bigint,
    patientid          bigint,
    targetid           bigint,
    targettype         varchar(255)
        constraint patient_billing_notes_targettype_check
            check ((targettype)::text = ANY
        ((ARRAY ['INVOICE'::character varying, 'CLAIM'::character varying, 'INSURANCE_PAYMENT'::character varying, 'PATIENT_PAYMENT'::character varying])::text[])),
    text               varchar(4000)
);

alter table patient_billing_notes
    owner to postgres;

create index idx_pbn_patient
    on patient_billing_notes (patientid);

create index idx_pbn_invoice
    on patient_billing_notes (invoiceid);

create index idx_pbn_type_target
    on patient_billing_notes (targettype, targetid);

create table patient_claims
(
    id                                bigint generated by default as identity
        primary key,
    created_by                        varchar(100),
    created_date                      timestamp(6) not null,
    last_modified_by                  varchar(100),
    last_modified_date                timestamp(6) not null,
    tenant_name                       varchar(100) not null,
    accidentdate                      varchar(255),
    admissiondate                     varchar(255),
    attachmentfile                    oid,
    attachmentindicator               varchar(255),
    attachmenttransmissioncode        varchar(255),
    attachmenttype                    varchar(255),
    attachments                       integer      not null,
    billingentity                     varchar(255),
    claimsubmissionreasoncode         varchar(255),
    createdon                         date,
    delayreasoncode                   varchar(255),
    diagnosticcode                    varchar(255),
    dischargedate                     varchar(255),
    documentcontrolnumber             varchar(255),
    eobattached                       boolean      not null,
    eobfile                           oid,
    insurancepaymentamount            varchar(255),
    invoiceid                         bigint       not null,
    labfacilityprimaryid              varchar(255),
    notes                             oid,
    orgid                             bigint       not null,
    patientid                         bigint       not null,
    payername                         varchar(255),
    predeterminationnumber            varchar(255),
    priorplacementdate                varchar(255),
    referraldate                      varchar(255),
    remittancedate                    varchar(255),
    serviceauthorizationexceptioncode varchar(255),
    servicelocationname               varchar(255),
    status                            varchar(255) not null
        constraint patient_claims_status_check
            check ((status)::text = ANY
        ((ARRAY ['DRAFT'::character varying, 'READY_FOR_SUBMISSION'::character varying, 'SUBMITTED'::character varying, 'IN_PROCESS'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'CLOSED'::character varying, 'VOID'::character varying])::text[])),
    treatingproviderid                varchar(255),
    type                              varchar(255)
);

alter table patient_claims
    owner to postgres;

create table patient_claim_documents
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    contenttype        varchar(255) not null,
    filename           varchar(255) not null,
    size               bigint       not null,
    storagekey         varchar(255) not null,
    type               varchar(20)  not null
        constraint patient_claim_documents_type_check
            check ((type)::text = ANY ((ARRAY ['ATTACHMENT'::character varying, 'EOB'::character varying])::text[])),
    claim_id           bigint       not null
        constraint fkr457w9bq7ryl3wekhya8qgfw0
            references patient_claims
);

alter table patient_claim_documents
    owner to postgres;

create index idx_claim_inv
    on patient_claims (invoiceid);

create table patient_code_lists
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    active             boolean      not null,
    codes              text,
    is_default         boolean,
    notes              text,
    order_index        integer,
    title              varchar(120) not null
);

alter table patient_code_lists
    owner to postgres;

create table patient_insurance_remit_lines
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    allowed            numeric(12, 2),
    applywriteoff      boolean,
    balance            numeric(12, 2),
    deductible         numeric(12, 2),
    inspay             numeric(12, 2),
    inswriteoff        numeric(12, 2),
    invoiceid          bigint       not null,
    invoicelineid      bigint       not null,
    orgid              bigint       not null,
    patientid          bigint       not null,
    submitted          numeric(12, 2),
    updateallowed      boolean,
    updateflatportion  boolean
);

alter table patient_insurance_remit_lines
    owner to postgres;

create table patient_invoices
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    backdate           date,
    insbalance         numeric(12, 2),
    inswo              numeric(12, 2),
    orgid              bigint       not null,
    patientid          bigint       not null,
    ptbalance          numeric(12, 2),
    status             varchar(255) not null
        constraint patient_invoices_status_check
            check ((status)::text = ANY
        ((ARRAY ['OPEN'::character varying, 'PARTIALLY_PAID'::character varying, 'PAID'::character varying, 'VOID'::character varying])::text[])),
    totalcharge        numeric(12, 2)
);

alter table patient_invoices
    owner to postgres;

create table patient_invoice_lines
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    allowed            numeric(12, 2),
    charge             numeric(12, 2),
    code               varchar(255),
    dos                date,
    insportion         numeric(12, 2),
    inswriteoff        numeric(12, 2),
    patientportion     numeric(12, 2),
    provider           varchar(255),
    treatment          varchar(255),
    invoice_id         bigint
        constraint fk3avo7an82nt7m4s3iqr2m85tn
            references patient_invoices
);

alter table patient_invoice_lines
    owner to postgres;

create table patient_medical_history
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    condition_name     varchar(255),
    description        text,
    diagnosis_date     timestamp(6),
    diagnosis_details  text,
    e_signed           boolean,
    encounter_id       bigint       not null,
    external_id        varchar(255),
    is_chronic         boolean,
    medical_condition  varchar(255),
    notes              text,
    onset_date         date,
    patient_id         bigint       not null,
    printed_at         timestamp(6) with time zone,
    resolved_date      date,
    signed_at          timestamp(6) with time zone,
    signed_by          varchar(128),
    status             varchar(50),
    treatment_details  text
);

alter table patient_medical_history
    owner to postgres;

create table patient_payments
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6)   not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6)   not null,
    tenant_name        varchar(100)   not null,
    amount             numeric(38, 2) not null,
    invoice_id         bigint,
    patient_id         bigint,
    payment_method     varchar(50)    not null
        constraint patient_payments_payment_method_check
            check ((payment_method)::text = ANY
        ((ARRAY ['CASH'::character varying, 'CREDIT_CARD'::character varying, 'DEBIT_CARD'::character varying, 'CHECK'::character varying, 'EFT'::character varying, 'CARE_CREDIT'::character varying, 'VISA'::character varying, 'MASTER'::character varying, 'DISCOVER'::character varying, 'AMEX'::character varying])::text[]))
    );

alter table patient_payments
    owner to postgres;

create table patient_payment_allocations
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6)   not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6)   not null,
    tenant_name        varchar(100)   not null,
    amount             numeric(38, 2) not null,
    invoice_line_id    bigint
        constraint fkm2euc8qx3ph0ve6jed963dtf2
            references patient_invoice_lines,
    payment_id         bigint         not null
        constraint fkg9oy59a7wstm64ilp9wcbhqqj
            references patient_payments
);

alter table patient_payment_allocations
    owner to postgres;

create table patienteducation
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    category           varchar(255),
    content            varchar(5000),
    externalid         varchar(255),
    language           varchar(255),
    readinglevel       varchar(255),
    summary            varchar(255),
    title              varchar(255)
);

alter table patienteducation
    owner to postgres;

create table patienteducationassignment
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    assigneddate       timestamp(6),
    delivered          boolean      not null,
    notes              varchar(255),
    patientid          bigint       not null,
    patientname        varchar(255),
    education_id       bigint       not null
        constraint fko9ltf1tbbsinvu144vfb3i43u
            references patienteducation
);

alter table patienteducationassignment
    owner to postgres;

create table payment_orders
(
    id                       bigint generated by default as identity
        primary key,
    created_by               varchar(100),
    created_date             timestamp(6) not null,
    last_modified_by         varchar(100),
    last_modified_date       timestamp(6) not null,
    tenant_name              varchar(100) not null,
    amount                   bigint       not null,
    card_id                  varchar(100),
    due_date                 timestamp(6),
    invoice_ids              oid,
    invoice_number           varchar(50),
    method                   varchar(20)  not null,
    paid_at                  timestamp(6),
    receipt_url              varchar(255),
    status                   varchar(20)  not null
        constraint payment_orders_status_check
            check ((status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'PAID'::character varying, 'FAILED'::character varying])::text[])),
    stripe_payment_intent_id varchar(100)
        constraint uks503arlorgy2qfj8ouu2h1sga
            unique
);

alter table payment_orders
    owner to postgres;

create table physical_exam
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    e_signed           boolean,
    encounter_id       bigint       not null,
    external_id        varchar(255),
    patient_id         bigint       not null,
    printed_at         timestamp(6) with time zone,
    signed_at          timestamp(6) with time zone,
    signed_by          varchar(128)
);

alter table physical_exam
    owner to postgres;

create table physical_exam_section
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    all_normal         boolean,
    findings           varchar(4000),
    normal_text        varchar(2000),
    section_key        varchar(48)  not null,
    physical_exam_id   bigint       not null
        constraint fkpktdwn2xhyygcrfgmgcbfj1e1
            references physical_exam
);

alter table physical_exam_section
    owner to postgres;

create table plan
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    diagnostic_plan    text,
    e_signed           boolean,
    encounter_id       bigint       not null,
    follow_up_visit    varchar(255),
    notes              text,
    orgid              bigint,
    patient_id         bigint       not null,
    plan               text,
    printed_at         timestamp(6) with time zone,
    return_work_school varchar(255),
    sections_json      text,
    signed_at          timestamp(6) with time zone,
    signed_by          varchar(128)
);

alter table plan
    owner to postgres;

create table portal_profiles
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    city               varchar(100),
    country            varchar(100),
    dateofbirth        date,
    email              varchar(150) not null
        constraint ukjolj1f4sq9rc195r8mut97jjs
            unique,
    firstname          varchar(100) not null,
    lastname           varchar(100) not null,
    phone              varchar(20),
    postalcode         varchar(20),
    state              varchar(100),
    street             varchar(255),
    user_id            bigint       not null
        constraint uk2ogbe3nt3lqcyopt2bfgwa41b
            unique
);

alter table portal_profiles
    owner to postgres;

create table procedure_item
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    cpt4               varchar(16),
    description        varchar(1024),
    encounter_id       bigint       not null,
    external_id        varchar(255),
    hb_end             varchar(32),
    hb_start           varchar(32),
    modifier1          varchar(10),
    modifier2          varchar(10),
    modifier3          varchar(10),
    modifier4          varchar(10),
    note               text,
    patient_id         bigint       not null,
    price_level_id     integer,
    price_level_title  text,
    provider_name      varchar(255),
    rate               varchar(64),
    related_icds       varchar(512),
    units              integer
);

alter table procedure_item
    owner to postgres;

create table provider
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    address            varchar(255),
    date_of_birth      varchar(255),
    email              varchar(255),
    external_id        varchar(255),
    fax_number         varchar(255),
    first_name         varchar(255),
    gender             varchar(255),
    last_name          varchar(255),
    license_expiry     varchar(255),
    license_number     varchar(255),
    license_state      varchar(255),
    middle_name        varchar(255),
    mobile_number      varchar(255),
    npi                varchar(255),
    phone_number       varchar(255),
    photo              varchar(255),
    prefix             varchar(255),
    provider_type      varchar(255),
    specialty          varchar(255),
    status             varchar(255)
        constraint provider_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'ARCHIVED'::character varying])::text[])),
    suffix             varchar(255)
);

alter table provider
    owner to postgres;

create table provider_note
(
    id                     bigint generated by default as identity
        primary key,
    created_by             varchar(100),
    created_date           timestamp(6) not null,
    last_modified_by       varchar(100),
    last_modified_date     timestamp(6) not null,
    tenant_name            varchar(100) not null,
    assessment             text,
    author_practitioner_id bigint,
    e_signed               boolean,
    encounter_id           bigint       not null,
    external_id            varchar(255),
    narrative              text,
    note_datetime          timestamp(6),
    note_status            varchar(255),
    note_title             varchar(255),
    note_type_code         varchar(255),
    objective              text,
    patient_id             bigint       not null,
    plan                   text,
    printed_at             timestamp(6) with time zone,
    signed_at              timestamp(6) with time zone,
    signed_by              varchar(128),
    subjective             text
);

alter table provider_note
    owner to postgres;

create table provider_signatures
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    comments           text,
    encounter_id       bigint       not null,
    external_id        varchar(255),
    patient_id         bigint       not null,
    signature_data     text,
    signature_format   varchar(64),
    signature_hash     varchar(128),
    signature_type     varchar(32),
    signed_at          varchar(40)  not null,
    signed_by          varchar(128),
    signer_role        varchar(64),
    status             varchar(64)
);

alter table provider_signatures
    owner to postgres;

create table recall
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    address            varchar(255),
    city               varchar(255),
    dob                varchar(255),
    email              varchar(255),
    emailconsent       boolean      not null,
    externalid         varchar(255),
    lastvisit          varchar(255),
    patientid          bigint,
    patientname        varchar(255),
    phone              varchar(255),
    providerid         bigint,
    recalldate         varchar(255),
    recallreason       varchar(255),
    smsconsent         boolean      not null,
    state              varchar(255),
    zipcode            varchar(255)
);

alter table recall
    owner to postgres;

create table referral_practices
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    address            varchar(255),
    city               varchar(255),
    country            varchar(255),
    email              varchar(255),
    fhir_id            varchar(255),
    name               varchar(255) not null,
    phone_number       varchar(255),
    postal_code        varchar(255),
    state              varchar(255)
);

alter table referral_practices
    owner to postgres;

create table referral_providers
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    address            varchar(255),
    city               varchar(255),
    country            varchar(255),
    email              varchar(255),
    fhir_id            varchar(255),
    name               varchar(255) not null,
    phone_number       varchar(255),
    postal_code        varchar(255),
    specialty          varchar(255),
    state              varchar(255),
    practice_id        bigint       not null
        constraint fko01009pj9lx253p45h40627f7
            references referral_practices
);

alter table referral_providers
    owner to postgres;

create table review_of_systems
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    e_signed           boolean,
    encounter_id       bigint       not null,
    external_id        varchar(255),
    is_negative        boolean,
    notes              text,
    patient_id         bigint       not null,
    printed_at         timestamp(6) with time zone,
    signed_at          timestamp(6) with time zone,
    signed_by          varchar(128),
    system_name        varchar(64)  not null
);

alter table review_of_systems
    owner to postgres;

create table review_of_system_details
(
    ros_id bigint not null
        constraint fki66q2igj3y3m8f5b873ea7fbk
            references review_of_systems,
    detail varchar(128)
);

alter table review_of_system_details
    owner to postgres;

create table schedules
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    external_id        varchar(255),
    provider_id        bigint       not null
);

alter table schedules
    owner to postgres;

create table services
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    default_price      varchar(255),
    name               varchar(255) not null
        constraint ukh4rqgjwnqidx6mvj4i22dxwxe
            unique
);

alter table services
    owner to postgres;

create table signoff
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    attestation_text   text,
    comments           text,
    content_hash       varchar(128),
    encounter_id       bigint       not null,
    external_id        varchar(255),
    patient_id         bigint       not null,
    printed_at         timestamp(6),
    signature_data     text,
    signature_type     varchar(32),
    signed_at          varchar(40),
    signed_by          varchar(128),
    signer_role        varchar(64),
    status             varchar(24),
    target_id          bigint,
    target_type        varchar(32),
    target_version     varchar(64)
);

alter table signoff
    owner to postgres;

create table slots
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    external_id        varchar(255),
    provider_id        bigint       not null
);

alter table slots
    owner to postgres;

create table social_history
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    e_signed           boolean,
    encounter_id       bigint       not null,
    external_id        varchar(255),
    patient_id         bigint       not null,
    printed_at         timestamp(6) with time zone,
    signed_at          timestamp(6) with time zone,
    signed_by          varchar(128)
);

alter table social_history
    owner to postgres;

create table social_history_entry
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    category           varchar(48)  not null,
    details            varchar(2000),
    value              varchar(255),
    social_history_id  bigint       not null
        constraint fk1eijtmgnwamcwe0s3yautgldv
            references social_history
);

alter table social_history_entry
    owner to postgres;

create table subscriptions
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    billing_cycle      varchar(255) not null,
    price              numeric(12, 2),
    service            varchar(255) not null,
    start_date         timestamp(6),
    status             varchar(255),
    user_id            bigint
);

alter table subscriptions
    owner to postgres;

create table suppliers
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    contact            varchar(255),
    email              varchar(255),
    externalid         varchar(255),
    name               varchar(255),
    phone              varchar(255)
);

alter table suppliers
    owner to postgres;

create table templates
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    body               text,
    external_id        varchar(255),
    subject            varchar(255),
    template_name      varchar(255) not null
);

alter table templates
    owner to postgres;

create table vitals
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    bmi                double precision,
    bpdiastolic        double precision,
    bpsystolic         double precision,
    encounterid        bigint,
    heightcm           double precision,
    heightin           double precision,
    notes              varchar(255),
    oxygensaturation   double precision,
    patientid          bigint,
    pulse              double precision,
    recordedat         timestamp(6),
    respiration        double precision,
    signed             boolean,
    temperaturec       double precision,
    temperaturef       double precision,
    weightkg           double precision,
    weightlbs          double precision
);

alter table vitals
    owner to postgres;

create table portal_users
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    approved_by        bigint,
    approved_date      timestamp(6),
    email              varchar(255) not null
        constraint ukdpc6ag4ff6k4ntetycw2qhbnf
            unique,
    first_name         varchar(255) not null,
    last_name          varchar(255) not null,
    password           varchar(255) not null,
    phone_number       varchar(255),
    reason             varchar(500),
    rejected_by        bigint,
    rejected_date      timestamp(6),
    status             varchar(255) not null
        constraint portal_users_status_check
            check ((status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])),
    uuid               uuid         not null
        constraint ukjx6kcmfuog452dv0cnkgd46ir
            unique
);

alter table portal_users
    owner to postgres;

create table portal_patients
(
    id                             bigint generated by default as identity
        primary key,
    created_by                     varchar(100),
    created_date                   timestamp(6) not null,
    last_modified_by               varchar(100),
    last_modified_date             timestamp(6) not null,
    tenant_name                    varchar(100) not null,
    address_line1                  varchar(255),
    address_line2                  varchar(255),
    city                           varchar(100),
    country                        varchar(50),
    date_of_birth                  date         not null,
    ehr_patient_id                 bigint,
    emergency_contact_name         varchar(255),
    emergency_contact_phone        varchar(20),
    emergency_contact_relationship varchar(100),
    gender                         varchar(10),
    medical_record_number          varchar(50),
    postal_code                    varchar(20),
    state                          varchar(50),
    portal_user_id                 bigint       not null
        constraint uknla0x549taua32m2gvfksrt1a
            unique
        constraint fk1slysb15vjtbnpgdgumqqf293
            references portal_users
);

alter table portal_patients
    owner to postgres;

create table portal_demographics
(
    id                    bigint generated by default as identity
        primary key,
    created_by            varchar(100),
    created_date          timestamp(6) not null,
    last_modified_by      varchar(100),
    last_modified_date    timestamp(6) not null,
    tenant_name           varchar(100) not null,
    address               varchar(255),
    allowemail            boolean      not null,
    allowmailmessage      boolean      not null,
    allowsms              boolean      not null,
    allowvoicemessage     boolean      not null,
    city                  varchar(255),
    contactemail          varchar(255),
    country               varchar(255),
    dob                   date,
    emergencycontactname  varchar(255),
    emergencycontactphone varchar(255),
    firstname             varchar(255),
    lastname              varchar(255),
    maritalstatus         varchar(255),
    middlename            varchar(255),
    phonemobile           varchar(255),
    postalcode            varchar(255),
    sex                   varchar(255),
    state                 varchar(255),
    patient_id            bigint
        constraint ukfdxwi5j6b93i8kbgvpk6oee0n
            unique
        constraint fk9p3cf5vybdhv146un1tnm804b
            references portal_patients
);

alter table portal_demographics
    owner to postgres;

create table admin_templates
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(100),
    created_date       timestamp(6) not null,
    last_modified_by   varchar(100),
    last_modified_date timestamp(6) not null,
    tenant_name        varchar(100) not null,
    locations          varchar(255) not null,
    practice_type      varchar(255) not null
);

alter table admin_templates
    owner to postgres;

create table audit_log
(
    id                  bigint generated by default as identity
        primary key,
    action_type         varchar(50)  not null,
    compliance_critical boolean      not null,
    consent_reference   varchar(100),
    data_classification varchar(255)
        constraint audit_log_data_classification_check
            check ((data_classification)::text = ANY
        ((ARRAY ['PUBLIC'::character varying, 'INTERNAL'::character varying, 'CONFIDENTIAL'::character varying, 'PHI'::character varying, 'SENSITIVE_PHI'::character varying])::text[])),
    description         varchar(500) not null,
    details             text,
    endpoint            varchar(500),
    entity_id           varchar(100),
    entity_type         varchar(100) not null,
    error_message       varchar(1000),
    event_time          timestamp(6) not null,
    http_method         varchar(10),
    ip_address          varchar(45),
    organization_id     bigint,
    patient_id          bigint,
    response_status     integer,
    risk_level          varchar(255) not null
        constraint audit_log_risk_level_check
            check ((risk_level)::text = ANY
                   ((ARRAY ['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[])),
    session_id          varchar(255),
    success             boolean      not null,
    user_agent          varchar(500),
    user_id             varchar(100) not null,
    user_role           varchar(50)  not null
);

alter table audit_log
    owner to postgres;

create index idx_audit_user_id
    on audit_log (user_id);

create index idx_audit_event_time
    on audit_log (event_time);

create index idx_audit_action_type
    on audit_log (action_type);

create index idx_audit_entity_type
    on audit_log (entity_type);

create index idx_audit_patient_id
    on audit_log (patient_id);

create index idx_audit_ip_address
    on audit_log (ip_address);

create index idx_audit_session_id
    on audit_log (session_id);

