-- Comprehensive demographics field config — Tier 1/2/3 fields
-- Adds: consent, guardian, guarantor, pharmacy, advance directives, additional IDs,
--        plus missing USCDI fields (suffix, gender identity, pronouns, deceased, etc.)
UPDATE tab_field_config
SET field_config = '{
  "sections": [
    {
      "key": "personal-info",
      "title": "Personal Information",
      "columns": 3,
      "collapsible": true,
      "collapsed": false,
      "fields": [
        {"key": "firstName", "label": "First Name", "type": "text", "required": true, "colSpan": 1, "placeholder": "First name",
         "fhirMapping": {"resource": "Patient", "path": "name[0].given[0]", "type": "string"}, "showInTable": true},
        {"key": "lastName", "label": "Last Name", "type": "text", "required": true, "colSpan": 1, "placeholder": "Last name",
         "fhirMapping": {"resource": "Patient", "path": "name[0].family", "type": "string"}, "showInTable": true},
        {"key": "middleName", "label": "Middle Name", "type": "text", "required": false, "colSpan": 1, "placeholder": "Middle name",
         "fhirMapping": {"resource": "Patient", "path": "name[0].given[1]", "type": "string"}},
        {"key": "suffix", "label": "Suffix", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "Jr.", "label": "Jr."}, {"value": "Sr.", "label": "Sr."}, {"value": "II", "label": "II"}, {"value": "III", "label": "III"}, {"value": "IV", "label": "IV"}, {"value": "MD", "label": "MD"}, {"value": "PhD", "label": "PhD"}],
         "fhirMapping": {"resource": "Patient", "path": "name[0].suffix[0]", "type": "string"}},
        {"key": "preferredName", "label": "Preferred Name", "type": "text", "required": false, "colSpan": 1, "placeholder": "Preferred / Nickname",
         "fhirMapping": {"resource": "Patient", "path": "name[1].given[0]", "type": "string"}},
        {"key": "previousLastName", "label": "Previous / Maiden Name", "type": "text", "required": false, "colSpan": 1, "placeholder": "Maiden or previous last name",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName].valueString", "type": "string"}},
        {"key": "dateOfBirth", "label": "Date of Birth", "type": "date", "required": true, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "birthDate", "type": "date"}, "showInTable": true},
        {"key": "gender", "label": "Sex at Birth", "type": "select", "required": true, "colSpan": 1,
         "options": [{"value": "male", "label": "Male"}, {"value": "female", "label": "Female"}, {"value": "other", "label": "Other"}, {"value": "unknown", "label": "Unknown"}],
         "fhirMapping": {"resource": "Patient", "path": "gender", "type": "code"}, "showInTable": true},
        {"key": "genderIdentity", "label": "Gender Identity", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "male", "label": "Male"}, {"value": "female", "label": "Female"}, {"value": "non-binary", "label": "Non-binary"}, {"value": "transgender-male", "label": "Transgender Male"}, {"value": "transgender-female", "label": "Transgender Female"}, {"value": "other", "label": "Other"}, {"value": "not-disclosed", "label": "Choose not to disclose"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://hl7.org/fhir/StructureDefinition/patient-genderIdentity].valueCode", "type": "code"}},
        {"key": "pronouns", "label": "Pronouns", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "he-him", "label": "He/Him"}, {"value": "she-her", "label": "She/Her"}, {"value": "they-them", "label": "They/Them"}, {"value": "other", "label": "Other"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://hl7.org/fhir/StructureDefinition/individual-pronouns].valueCode", "type": "code"}},
        {"key": "sexualOrientation", "label": "Sexual Orientation", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "straight", "label": "Straight / Heterosexual"}, {"value": "gay", "label": "Gay"}, {"value": "lesbian", "label": "Lesbian"}, {"value": "bisexual", "label": "Bisexual"}, {"value": "other", "label": "Something else"}, {"value": "unknown", "label": "Don''t know"}, {"value": "not-disclosed", "label": "Choose not to disclose"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://hl7.org/fhir/StructureDefinition/patient-sexualOrientation].valueCode", "type": "code"}},
        {"key": "mrn", "label": "Medical Record Number", "type": "text", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "identifier.where(system=''http://ciyex.org/fhir/sid/mrn'').value", "type": "string"}, "showInTable": true},
        {"key": "ssn", "label": "SSN", "type": "text", "required": false, "colSpan": 1, "placeholder": "XXX-XX-XXXX",
         "fhirMapping": {"resource": "Patient", "path": "identifier.where(system=''http://hl7.org/fhir/sid/us-ssn'').value", "type": "string"}},
        {"key": "maritalStatus", "label": "Marital Status", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "S", "label": "Single"}, {"value": "M", "label": "Married"}, {"value": "D", "label": "Divorced"}, {"value": "W", "label": "Widowed"}, {"value": "T", "label": "Domestic Partner"}, {"value": "L", "label": "Legally Separated"}],
         "fhirMapping": {"resource": "Patient", "path": "maritalStatus.coding[0].code", "type": "code"}},
        {"key": "race", "label": "Race", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "2106-3", "label": "White"}, {"value": "2054-5", "label": "Black or African American"}, {"value": "2028-9", "label": "Asian"}, {"value": "1002-5", "label": "American Indian or Alaska Native"}, {"value": "2076-8", "label": "Native Hawaiian or Pacific Islander"}, {"value": "2131-1", "label": "Other Race"}, {"value": "ASKU", "label": "Asked but unknown"}, {"value": "UNK", "label": "Unknown"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://hl7.org/fhir/us/core/StructureDefinition/us-core-race].valueCode", "type": "code"}},
        {"key": "ethnicity", "label": "Ethnicity", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "2135-2", "label": "Hispanic or Latino"}, {"value": "2186-5", "label": "Not Hispanic or Latino"}, {"value": "UNK", "label": "Unknown"}, {"value": "ASKU", "label": "Asked but unknown"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity].valueCode", "type": "code"}},
        {"key": "language", "label": "Preferred Language", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "en", "label": "English"}, {"value": "es", "label": "Spanish"}, {"value": "zh", "label": "Chinese"}, {"value": "vi", "label": "Vietnamese"}, {"value": "ko", "label": "Korean"}, {"value": "tl", "label": "Tagalog"}, {"value": "fr", "label": "French"}, {"value": "ar", "label": "Arabic"}, {"value": "de", "label": "German"}, {"value": "ru", "label": "Russian"}, {"value": "pt", "label": "Portuguese"}, {"value": "hi", "label": "Hindi"}, {"value": "ja", "label": "Japanese"}, {"value": "other", "label": "Other"}],
         "fhirMapping": {"resource": "Patient", "path": "communication[0].language.coding[0].code", "type": "code"}},
        {"key": "interpreterNeeded", "label": "Interpreter Needed", "type": "toggle", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://hl7.org/fhir/StructureDefinition/patient-interpreterRequired].valueBoolean", "type": "boolean"}},
        {"key": "tribalAffiliation", "label": "Tribal Affiliation", "type": "text", "required": false, "colSpan": 1, "placeholder": "Tribal affiliation",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://hl7.org/fhir/us/core/StructureDefinition/us-core-tribal-affiliation].valueString", "type": "string"}},
        {"key": "religion", "label": "Religion", "type": "combobox", "required": false, "colSpan": 1,
         "options": [{"value": "christian", "label": "Christian"}, {"value": "catholic", "label": "Catholic"}, {"value": "jewish", "label": "Jewish"}, {"value": "muslim", "label": "Muslim"}, {"value": "hindu", "label": "Hindu"}, {"value": "buddhist", "label": "Buddhist"}, {"value": "none", "label": "None"}, {"value": "other", "label": "Other"}, {"value": "not-disclosed", "label": "Choose not to disclose"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://hl7.org/fhir/StructureDefinition/patient-religion].valueCode", "type": "code"}},
        {"key": "veteranStatus", "label": "Veteran Status", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "yes", "label": "Veteran"}, {"value": "no", "label": "Non-Veteran"}, {"value": "unknown", "label": "Unknown"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/veteran-status].valueCode", "type": "code"}},
        {"key": "disabilityStatus", "label": "Disability Status", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "yes", "label": "Yes"}, {"value": "no", "label": "No"}, {"value": "not-disclosed", "label": "Choose not to disclose"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/disability-status].valueCode", "type": "code"}},
        {"key": "multipleBirth", "label": "Multiple Birth", "type": "toggle", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "multipleBirthBoolean", "type": "boolean"}},
        {"key": "deceasedDate", "label": "Date of Death", "type": "date", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "deceasedDateTime", "type": "datetime"}},
        {"key": "patientPhoto", "label": "Photo", "type": "text", "required": false, "colSpan": 1, "placeholder": "Photo URL",
         "fhirMapping": {"resource": "Patient", "path": "photo[0].url", "type": "string"}}
      ]
    },
    {
      "key": "contact-info",
      "title": "Contact Information",
      "columns": 3,
      "collapsible": true,
      "collapsed": false,
      "fields": [
        {"key": "phoneNumber", "label": "Mobile Phone", "type": "phone", "required": false, "colSpan": 1, "placeholder": "(555) 123-4567",
         "fhirMapping": {"resource": "Patient", "path": "telecom.where(system=''phone'').value", "type": "string"}, "showInTable": true},
        {"key": "homePhone", "label": "Home Phone", "type": "phone", "required": false, "colSpan": 1, "placeholder": "(555) 123-4567",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/home-phone].valueString", "type": "string"}},
        {"key": "workPhone", "label": "Work Phone", "type": "phone", "required": false, "colSpan": 1, "placeholder": "(555) 123-4567",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/work-phone].valueString", "type": "string"}},
        {"key": "email", "label": "Email Address", "type": "email", "required": false, "colSpan": 1, "placeholder": "email@example.com",
         "fhirMapping": {"resource": "Patient", "path": "telecom.where(system=''email'').value", "type": "string"}, "showInTable": true},
        {"key": "preferredContactMethod", "label": "Preferred Contact Method", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "phone", "label": "Phone"}, {"value": "email", "label": "Email"}, {"value": "text", "label": "Text/SMS"}, {"value": "mail", "label": "Mail"}, {"value": "portal", "label": "Patient Portal"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/preferred-contact-method].valueCode", "type": "code"}},
        {"key": "address", "label": "Address", "type": "address", "required": false, "colSpan": 3,
         "fhirMapping": {"resource": "Patient", "path": "address[0]", "type": "address"}}
      ]
    },
    {
      "key": "communication-consent",
      "title": "Communication Consent",
      "columns": 3,
      "collapsible": true,
      "collapsed": false,
      "fields": [
        {"key": "allowSms", "label": "Allow SMS / Text Messages", "type": "toggle", "required": false, "colSpan": 1,
         "helpText": "TCPA requires explicit consent before sending text messages",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/hipaa-allow-sms].valueBoolean", "type": "boolean"}},
        {"key": "allowEmail", "label": "Allow Email Communication", "type": "toggle", "required": false, "colSpan": 1,
         "helpText": "Consent to receive health information via email",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/hipaa-allow-email].valueBoolean", "type": "boolean"}},
        {"key": "allowVoicemail", "label": "Allow Voicemail", "type": "toggle", "required": false, "colSpan": 1,
         "helpText": "OK to leave PHI in voicemail messages",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/hipaa-allow-voicemail].valueBoolean", "type": "boolean"}},
        {"key": "allowMail", "label": "Allow Postal Mail", "type": "toggle", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/hipaa-allow-mail].valueBoolean", "type": "boolean"}},
        {"key": "allowPatientPortal", "label": "Allow Patient Portal", "type": "toggle", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/allow-patient-portal].valueBoolean", "type": "boolean"}},
        {"key": "hipaaNPPReceived", "label": "HIPAA Notice Received", "type": "toggle", "required": false, "colSpan": 1,
         "helpText": "Patient acknowledged Notice of Privacy Practices",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/hipaa-npp-received].valueBoolean", "type": "boolean"}},
        {"key": "allowHIE", "label": "Allow Health Info Exchange", "type": "toggle", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/allow-hie].valueBoolean", "type": "boolean"}},
        {"key": "allowImmunizationRegistry", "label": "Allow Immunization Registry", "type": "toggle", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/allow-imm-registry].valueBoolean", "type": "boolean"}},
        {"key": "medicationHistoryConsent", "label": "Medication History Consent", "type": "toggle", "required": false, "colSpan": 1,
         "helpText": "Consent for PDMP / Rx history queries",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/med-history-consent].valueBoolean", "type": "boolean"}}
      ]
    },
    {
      "key": "emergency-contact",
      "title": "Emergency Contact",
      "columns": 3,
      "collapsible": true,
      "collapsed": false,
      "fields": [
        {"key": "emergencyName", "label": "Contact Name", "type": "text", "required": false, "colSpan": 1, "placeholder": "Full name",
         "fhirMapping": {"resource": "Patient", "path": "contact[0].name.text", "type": "string"}},
        {"key": "emergencyRelationship", "label": "Relationship", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "spouse", "label": "Spouse"}, {"value": "parent", "label": "Parent"}, {"value": "child", "label": "Child"}, {"value": "sibling", "label": "Sibling"}, {"value": "friend", "label": "Friend"}, {"value": "other", "label": "Other"}],
         "fhirMapping": {"resource": "Patient", "path": "contact[0].relationship[0].text", "type": "string"}},
        {"key": "emergencyPhone", "label": "Phone", "type": "phone", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "contact[0].telecom[0].value", "type": "string"}}
      ]
    },
    {
      "key": "guardian-info",
      "title": "Guardian Information",
      "columns": 3,
      "collapsible": true,
      "collapsed": true,
      "fields": [
        {"key": "guardianName", "label": "Guardian Name", "type": "text", "required": false, "colSpan": 1, "placeholder": "Full name",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/guardian-name].valueString", "type": "string"}},
        {"key": "guardianRelationship", "label": "Relationship", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "parent", "label": "Parent"}, {"value": "legal-guardian", "label": "Legal Guardian"}, {"value": "grandparent", "label": "Grandparent"}, {"value": "foster-parent", "label": "Foster Parent"}, {"value": "other", "label": "Other"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/guardian-relationship].valueCode", "type": "code"}},
        {"key": "guardianPhone", "label": "Phone", "type": "phone", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/guardian-phone].valueString", "type": "string"}},
        {"key": "guardianEmail", "label": "Email", "type": "email", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/guardian-email].valueString", "type": "string"}},
        {"key": "guardianAddress", "label": "Address", "type": "text", "required": false, "colSpan": 2, "placeholder": "Full address",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/guardian-address].valueString", "type": "string"}},
        {"key": "mothersName", "label": "Mother''s Name", "type": "text", "required": false, "colSpan": 1, "placeholder": "Mother''s full name",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/mothers-name].valueString", "type": "string"}}
      ]
    },
    {
      "key": "guarantor-info",
      "title": "Guarantor / Billing Responsible Party",
      "columns": 3,
      "collapsible": true,
      "collapsed": true,
      "fields": [
        {"key": "guarantorFirstName", "label": "First Name", "type": "text", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/guarantor-first-name].valueString", "type": "string"}},
        {"key": "guarantorLastName", "label": "Last Name", "type": "text", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/guarantor-last-name].valueString", "type": "string"}},
        {"key": "guarantorRelationship", "label": "Relationship to Patient", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "self", "label": "Self"}, {"value": "spouse", "label": "Spouse"}, {"value": "parent", "label": "Parent"}, {"value": "guardian", "label": "Guardian"}, {"value": "other", "label": "Other"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/guarantor-relationship].valueCode", "type": "code"}},
        {"key": "guarantorDOB", "label": "Date of Birth", "type": "date", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/guarantor-dob].valueDate", "type": "date"}},
        {"key": "guarantorSSN", "label": "SSN", "type": "text", "required": false, "colSpan": 1, "placeholder": "XXX-XX-XXXX",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/guarantor-ssn].valueString", "type": "string"}},
        {"key": "guarantorPhone", "label": "Phone", "type": "phone", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/guarantor-phone].valueString", "type": "string"}},
        {"key": "guarantorEmail", "label": "Email", "type": "email", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/guarantor-email].valueString", "type": "string"}},
        {"key": "guarantorAddress", "label": "Address", "type": "text", "required": false, "colSpan": 2, "placeholder": "Full address",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/guarantor-address].valueString", "type": "string"}},
        {"key": "guarantorEmployer", "label": "Employer", "type": "text", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/guarantor-employer].valueString", "type": "string"}}
      ]
    },
    {
      "key": "pharmacy",
      "title": "Preferred Pharmacy",
      "columns": 3,
      "collapsible": true,
      "collapsed": true,
      "fields": [
        {"key": "pharmacyName", "label": "Pharmacy Name", "type": "text", "required": false, "colSpan": 1, "placeholder": "Pharmacy name",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/pharmacy-name].valueString", "type": "string"}},
        {"key": "pharmacyPhone", "label": "Phone", "type": "phone", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/pharmacy-phone].valueString", "type": "string"}},
        {"key": "pharmacyFax", "label": "Fax", "type": "phone", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/pharmacy-fax].valueString", "type": "string"}},
        {"key": "pharmacyAddress", "label": "Address", "type": "text", "required": false, "colSpan": 2, "placeholder": "Pharmacy address",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/pharmacy-address].valueString", "type": "string"}},
        {"key": "mailOrderPharmacy", "label": "Mail-Order Pharmacy", "type": "text", "required": false, "colSpan": 1, "placeholder": "Mail-order pharmacy name",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/mail-order-pharmacy].valueString", "type": "string"}}
      ]
    },
    {
      "key": "advance-directives",
      "title": "Advance Directives",
      "columns": 3,
      "collapsible": true,
      "collapsed": true,
      "fields": [
        {"key": "advanceDirectiveOnFile", "label": "Advance Directive on File", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "yes", "label": "Yes"}, {"value": "no", "label": "No"}, {"value": "unknown", "label": "Unknown"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/advance-directive-on-file].valueCode", "type": "code"}},
        {"key": "advanceDirectiveType", "label": "Directive Type", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "living-will", "label": "Living Will"}, {"value": "healthcare-proxy", "label": "Healthcare Proxy / POA"}, {"value": "polst", "label": "POLST/MOLST"}, {"value": "dnr", "label": "DNR"}, {"value": "dnar", "label": "DNAR"}, {"value": "multiple", "label": "Multiple"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/advance-directive-type].valueCode", "type": "code"}},
        {"key": "advanceDirectiveReviewDate", "label": "Review Date", "type": "date", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/advance-directive-review-date].valueDate", "type": "date"}},
        {"key": "healthcareProxyName", "label": "Healthcare Proxy / POA Name", "type": "text", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/healthcare-proxy-name].valueString", "type": "string"}},
        {"key": "healthcareProxyPhone", "label": "Healthcare Proxy Phone", "type": "phone", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/healthcare-proxy-phone].valueString", "type": "string"}},
        {"key": "organDonor", "label": "Organ Donor", "type": "select", "required": false, "colSpan": 1,
         "options": [{"value": "yes", "label": "Yes"}, {"value": "no", "label": "No"}, {"value": "unknown", "label": "Unknown"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/organ-donor].valueCode", "type": "code"}}
      ]
    },
    {
      "key": "provider-practice",
      "title": "Provider & Practice",
      "columns": 3,
      "collapsible": true,
      "collapsed": false,
      "fields": [
        {"key": "assignedProvider", "label": "Assigned Provider", "type": "lookup", "required": false, "colSpan": 1,
         "lookupConfig": {"endpoint": "/api/providers", "displayField": "name", "valueField": "id", "searchable": true},
         "fhirMapping": {"resource": "Patient", "path": "generalPractitioner[0].reference", "type": "reference"}},
        {"key": "referringProvider", "label": "Referring Provider", "type": "lookup", "required": false, "colSpan": 1,
         "lookupConfig": {"endpoint": "/api/providers", "displayField": "name", "valueField": "id", "searchable": true},
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/referring-provider].valueReference", "type": "reference"}},
        {"key": "primaryCarePhysician", "label": "Primary Care Physician", "type": "lookup", "required": false, "colSpan": 1,
         "lookupConfig": {"endpoint": "/api/providers", "displayField": "name", "valueField": "id", "searchable": true},
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/primary-care-physician].valueReference", "type": "reference"}},
        {"key": "status", "label": "Patient Status", "type": "select", "required": true, "colSpan": 1,
         "options": [{"value": "true", "label": "Active"}, {"value": "false", "label": "Inactive"}],
         "fhirMapping": {"resource": "Patient", "path": "active", "type": "boolean"}},
        {"key": "referralSource", "label": "Referral Source", "type": "combobox", "required": false, "colSpan": 1,
         "options": [{"value": "physician", "label": "Physician Referral"}, {"value": "self", "label": "Self / Walk-in"}, {"value": "insurance", "label": "Insurance"}, {"value": "web", "label": "Website"}, {"value": "friend", "label": "Friend / Family"}, {"value": "ad", "label": "Advertisement"}, {"value": "other", "label": "Other"}],
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/referral-source].valueString", "type": "string"}},
        {"key": "providerSinceDate", "label": "Patient Since", "type": "date", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/provider-since-date].valueDate", "type": "date"}}
      ]
    },
    {
      "key": "employer-info",
      "title": "Employer Information",
      "columns": 3,
      "collapsible": true,
      "collapsed": true,
      "fields": [
        {"key": "occupation", "label": "Occupation", "type": "text", "required": false, "colSpan": 1, "placeholder": "Job title",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/occupation].valueString", "type": "string"}},
        {"key": "industry", "label": "Industry", "type": "text", "required": false, "colSpan": 1, "placeholder": "Industry",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/industry].valueString", "type": "string"}},
        {"key": "employerName", "label": "Employer Name", "type": "text", "required": false, "colSpan": 1, "placeholder": "Employer name",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/employer-name].valueString", "type": "string"}},
        {"key": "employerPhone", "label": "Employer Phone", "type": "phone", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/employer-phone].valueString", "type": "string"}},
        {"key": "employerAddress", "label": "Employer Address", "type": "text", "required": false, "colSpan": 1, "placeholder": "Employer address",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/employer-address].valueString", "type": "string"}}
      ]
    },
    {
      "key": "additional-ids",
      "title": "Additional Identifiers",
      "columns": 3,
      "collapsible": true,
      "collapsed": true,
      "fields": [
        {"key": "driversLicense", "label": "Driver''s License #", "type": "text", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "identifier.where(system=''http://ciyex.org/fhir/sid/dl'').value", "type": "string"}},
        {"key": "driversLicenseState", "label": "DL State", "type": "text", "required": false, "colSpan": 1, "placeholder": "State",
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/dl-state].valueString", "type": "string"}},
        {"key": "medicaidId", "label": "Medicaid ID", "type": "text", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "identifier.where(system=''http://ciyex.org/fhir/sid/medicaid'').value", "type": "string"}},
        {"key": "medicareMBI", "label": "Medicare Beneficiary ID", "type": "text", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "identifier.where(system=''http://hl7.org/fhir/sid/us-mbi'').value", "type": "string"}},
        {"key": "registrationDate", "label": "Registration Date", "type": "date", "required": false, "colSpan": 1,
         "fhirMapping": {"resource": "Patient", "path": "extension[url=http://ciyex.org/fhir/ext/registration-date].valueDate", "type": "date"}}
      ]
    }
  ]
}'
WHERE tab_key = 'demographics' AND org_id = '*';
