-- =====================================================
-- V9: Move Encounters and Claims to top-level tab groups
-- =====================================================
-- Previously these were nested inside Clinical and Financial.
-- Now they are their own top-level groups for quick access.

-- Update general-practice
UPDATE practice_type SET default_tab_config = '[{"label":"Overview","position":0,"tabs":[{"key":"demographics","label":"Demographics","icon":"User","visible":true,"position":0},{"key":"insurance","label":"Insurance","icon":"Shield","visible":true,"position":1},{"key":"vitals","label":"Vitals","icon":"Activity","visible":true,"position":2},{"key":"allergies","label":"Allergies","icon":"AlertTriangle","visible":true,"position":3},{"key":"problem-list","label":"Problem List","icon":"ClipboardList","visible":true,"position":4}]},{"label":"Encounters","position":1,"tabs":[{"key":"encounters","label":"Encounters","icon":"Calendar","visible":true,"position":0},{"key":"appointments","label":"Appointments","icon":"Clock","visible":true,"position":1},{"key":"visit-notes","label":"Visit Notes","icon":"FileText","visible":true,"position":2},{"key":"referrals","label":"Referrals","icon":"Share2","visible":true,"position":3}]},{"label":"Clinical","position":2,"tabs":[{"key":"medications","label":"Medications","icon":"Pill","visible":true,"position":0},{"key":"lab-results","label":"Lab Results","icon":"TestTube","visible":true,"position":1},{"key":"immunizations","label":"Immunizations","icon":"Syringe","visible":true,"position":2},{"key":"procedures","label":"Procedures","icon":"Scissors","visible":true,"position":3}]},{"label":"Claims","position":3,"tabs":[{"key":"claims","label":"Claims","icon":"Receipt","visible":true,"position":0},{"key":"claim-submissions","label":"Submissions","icon":"Send","visible":true,"position":1},{"key":"claim-denials","label":"Denials","icon":"XCircle","visible":true,"position":2},{"key":"era-remittance","label":"ERA / Remittance","icon":"FileCheck","visible":true,"position":3}]},{"label":"General","position":4,"tabs":[{"key":"documents","label":"Documents","icon":"FileText","visible":true,"position":0},{"key":"education","label":"Education","icon":"GraduationCap","visible":true,"position":1},{"key":"messaging","label":"Messaging","icon":"MessageSquare","visible":true,"position":2}]},{"label":"Financial","position":5,"tabs":[{"key":"billing","label":"Billing","icon":"CreditCard","visible":true,"position":0},{"key":"payments","label":"Payments","icon":"DollarSign","visible":true,"position":1},{"key":"statements","label":"Statements","icon":"FileText","visible":true,"position":2}]}]'
WHERE code = 'general-practice';

-- Update internal-medicine
UPDATE practice_type SET default_tab_config = '[{"label":"Overview","position":0,"tabs":[{"key":"demographics","label":"Demographics","icon":"User","visible":true,"position":0},{"key":"insurance","label":"Insurance","icon":"Shield","visible":true,"position":1},{"key":"vitals","label":"Vitals","icon":"Activity","visible":true,"position":2},{"key":"allergies","label":"Allergies","icon":"AlertTriangle","visible":true,"position":3},{"key":"problem-list","label":"Problem List","icon":"ClipboardList","visible":true,"position":4}]},{"label":"Encounters","position":1,"tabs":[{"key":"encounters","label":"Encounters","icon":"Calendar","visible":true,"position":0},{"key":"appointments","label":"Appointments","icon":"Clock","visible":true,"position":1},{"key":"visit-notes","label":"Visit Notes","icon":"FileText","visible":true,"position":2},{"key":"referrals","label":"Referrals","icon":"Share2","visible":true,"position":3}]},{"label":"Clinical","position":2,"tabs":[{"key":"medications","label":"Medications","icon":"Pill","visible":true,"position":0},{"key":"lab-results","label":"Lab Results","icon":"TestTube","visible":true,"position":1},{"key":"immunizations","label":"Immunizations","icon":"Syringe","visible":true,"position":2},{"key":"procedures","label":"Procedures","icon":"Scissors","visible":true,"position":3},{"key":"imaging","label":"Imaging","icon":"Scan","visible":true,"position":4}]},{"label":"Claims","position":3,"tabs":[{"key":"claims","label":"Claims","icon":"Receipt","visible":true,"position":0},{"key":"claim-submissions","label":"Submissions","icon":"Send","visible":true,"position":1},{"key":"claim-denials","label":"Denials","icon":"XCircle","visible":true,"position":2},{"key":"era-remittance","label":"ERA / Remittance","icon":"FileCheck","visible":true,"position":3}]},{"label":"General","position":4,"tabs":[{"key":"documents","label":"Documents","icon":"FileText","visible":true,"position":0},{"key":"education","label":"Education","icon":"GraduationCap","visible":true,"position":1},{"key":"messaging","label":"Messaging","icon":"MessageSquare","visible":true,"position":2}]},{"label":"Financial","position":5,"tabs":[{"key":"billing","label":"Billing","icon":"CreditCard","visible":true,"position":0},{"key":"payments","label":"Payments","icon":"DollarSign","visible":true,"position":1},{"key":"statements","label":"Statements","icon":"FileText","visible":true,"position":2}]}]'
WHERE code = 'internal-medicine';

-- Update pediatrics
UPDATE practice_type SET default_tab_config = '[{"label":"Overview","position":0,"tabs":[{"key":"demographics","label":"Demographics","icon":"User","visible":true,"position":0},{"key":"insurance","label":"Insurance","icon":"Shield","visible":true,"position":1},{"key":"vitals","label":"Vitals","icon":"Activity","visible":true,"position":2},{"key":"growth-chart","label":"Growth Chart","icon":"TrendingUp","visible":true,"position":3},{"key":"allergies","label":"Allergies","icon":"AlertTriangle","visible":true,"position":4},{"key":"problem-list","label":"Problem List","icon":"ClipboardList","visible":true,"position":5}]},{"label":"Encounters","position":1,"tabs":[{"key":"encounters","label":"Encounters","icon":"Calendar","visible":true,"position":0},{"key":"appointments","label":"Appointments","icon":"Clock","visible":true,"position":1},{"key":"visit-notes","label":"Visit Notes","icon":"FileText","visible":true,"position":2},{"key":"referrals","label":"Referrals","icon":"Share2","visible":true,"position":3}]},{"label":"Clinical","position":2,"tabs":[{"key":"medications","label":"Medications","icon":"Pill","visible":true,"position":0},{"key":"immunizations","label":"Immunizations","icon":"Syringe","visible":true,"position":1},{"key":"lab-results","label":"Lab Results","icon":"TestTube","visible":true,"position":2},{"key":"developmental","label":"Developmental","icon":"Brain","visible":true,"position":3}]},{"label":"Claims","position":3,"tabs":[{"key":"claims","label":"Claims","icon":"Receipt","visible":true,"position":0},{"key":"claim-submissions","label":"Submissions","icon":"Send","visible":true,"position":1},{"key":"claim-denials","label":"Denials","icon":"XCircle","visible":true,"position":2},{"key":"era-remittance","label":"ERA / Remittance","icon":"FileCheck","visible":true,"position":3}]},{"label":"General","position":4,"tabs":[{"key":"documents","label":"Documents","icon":"FileText","visible":true,"position":0},{"key":"education","label":"Education","icon":"GraduationCap","visible":true,"position":1},{"key":"messaging","label":"Messaging","icon":"MessageSquare","visible":true,"position":2}]},{"label":"Financial","position":5,"tabs":[{"key":"billing","label":"Billing","icon":"CreditCard","visible":true,"position":0},{"key":"payments","label":"Payments","icon":"DollarSign","visible":true,"position":1},{"key":"statements","label":"Statements","icon":"FileText","visible":true,"position":2}]}]'
WHERE code = 'pediatrics';

-- Update orthopedic-surgery
UPDATE practice_type SET default_tab_config = '[{"label":"Overview","position":0,"tabs":[{"key":"demographics","label":"Demographics","icon":"User","visible":true,"position":0},{"key":"insurance","label":"Insurance","icon":"Shield","visible":true,"position":1},{"key":"vitals","label":"Vitals","icon":"Activity","visible":true,"position":2},{"key":"allergies","label":"Allergies","icon":"AlertTriangle","visible":true,"position":3},{"key":"surgical-history","label":"Surgical History","icon":"Scissors","visible":true,"position":4}]},{"label":"Encounters","position":1,"tabs":[{"key":"encounters","label":"Encounters","icon":"Calendar","visible":true,"position":0},{"key":"appointments","label":"Appointments","icon":"Clock","visible":true,"position":1},{"key":"visit-notes","label":"Visit Notes","icon":"FileText","visible":true,"position":2}]},{"label":"Clinical","position":2,"tabs":[{"key":"medications","label":"Medications","icon":"Pill","visible":true,"position":0},{"key":"imaging","label":"Imaging","icon":"Scan","visible":true,"position":1},{"key":"procedures","label":"Procedures","icon":"Scissors","visible":true,"position":2},{"key":"physical-therapy","label":"Physical Therapy","icon":"Dumbbell","visible":true,"position":3}]},{"label":"Claims","position":3,"tabs":[{"key":"claims","label":"Claims","icon":"Receipt","visible":true,"position":0},{"key":"claim-submissions","label":"Submissions","icon":"Send","visible":true,"position":1},{"key":"claim-denials","label":"Denials","icon":"XCircle","visible":true,"position":2},{"key":"prior-auth","label":"Prior Auth","icon":"ShieldCheck","visible":true,"position":3},{"key":"era-remittance","label":"ERA / Remittance","icon":"FileCheck","visible":true,"position":4}]},{"label":"General","position":4,"tabs":[{"key":"documents","label":"Documents","icon":"FileText","visible":true,"position":0},{"key":"referrals","label":"Referrals","icon":"Share2","visible":true,"position":1},{"key":"messaging","label":"Messaging","icon":"MessageSquare","visible":true,"position":2}]},{"label":"Financial","position":5,"tabs":[{"key":"billing","label":"Billing","icon":"CreditCard","visible":true,"position":0},{"key":"payments","label":"Payments","icon":"DollarSign","visible":true,"position":1},{"key":"statements","label":"Statements","icon":"FileText","visible":true,"position":2}]}]'
WHERE code = 'orthopedic-surgery';

-- Update psychiatry
UPDATE practice_type SET default_tab_config = '[{"label":"Overview","position":0,"tabs":[{"key":"demographics","label":"Demographics","icon":"User","visible":true,"position":0},{"key":"insurance","label":"Insurance","icon":"Shield","visible":true,"position":1},{"key":"vitals","label":"Vitals","icon":"Activity","visible":true,"position":2},{"key":"allergies","label":"Allergies","icon":"AlertTriangle","visible":true,"position":3},{"key":"problem-list","label":"Problem List","icon":"ClipboardList","visible":true,"position":4}]},{"label":"Encounters","position":1,"tabs":[{"key":"encounters","label":"Encounters","icon":"Calendar","visible":true,"position":0},{"key":"appointments","label":"Appointments","icon":"Clock","visible":true,"position":1},{"key":"visit-notes","label":"Visit Notes","icon":"FileText","visible":true,"position":2}]},{"label":"Clinical","position":2,"tabs":[{"key":"medications","label":"Medications","icon":"Pill","visible":true,"position":0},{"key":"assessments","label":"Assessments","icon":"ClipboardCheck","visible":true,"position":1},{"key":"treatment-plans","label":"Treatment Plans","icon":"Target","visible":true,"position":2},{"key":"progress-notes","label":"Progress Notes","icon":"FileText","visible":true,"position":3}]},{"label":"Claims","position":3,"tabs":[{"key":"claims","label":"Claims","icon":"Receipt","visible":true,"position":0},{"key":"claim-submissions","label":"Submissions","icon":"Send","visible":true,"position":1},{"key":"claim-denials","label":"Denials","icon":"XCircle","visible":true,"position":2},{"key":"era-remittance","label":"ERA / Remittance","icon":"FileCheck","visible":true,"position":3}]},{"label":"General","position":4,"tabs":[{"key":"documents","label":"Documents","icon":"FileText","visible":true,"position":0},{"key":"education","label":"Education","icon":"GraduationCap","visible":true,"position":1},{"key":"messaging","label":"Messaging","icon":"MessageSquare","visible":true,"position":2},{"key":"referrals","label":"Referrals","icon":"Share2","visible":true,"position":3}]},{"label":"Financial","position":5,"tabs":[{"key":"billing","label":"Billing","icon":"CreditCard","visible":true,"position":0},{"key":"payments","label":"Payments","icon":"DollarSign","visible":true,"position":1},{"key":"statements","label":"Statements","icon":"FileText","visible":true,"position":2}]}]'
WHERE code = 'psychiatry';

-- Update general-dentistry
UPDATE practice_type SET default_tab_config = '[{"label":"Overview","position":0,"tabs":[{"key":"demographics","label":"Demographics","icon":"User","visible":true,"position":0},{"key":"insurance","label":"Insurance","icon":"Shield","visible":true,"position":1},{"key":"allergies","label":"Allergies","icon":"AlertTriangle","visible":true,"position":2},{"key":"dental-history","label":"Dental History","icon":"FileText","visible":true,"position":3}]},{"label":"Encounters","position":1,"tabs":[{"key":"encounters","label":"Encounters","icon":"Calendar","visible":true,"position":0},{"key":"appointments","label":"Appointments","icon":"Clock","visible":true,"position":1},{"key":"visit-notes","label":"Visit Notes","icon":"FileText","visible":true,"position":2}]},{"label":"Clinical","position":2,"tabs":[{"key":"dental-chart","label":"Dental Chart","icon":"ClipboardList","visible":true,"position":0},{"key":"treatment-plan","label":"Treatment Plan","icon":"Target","visible":true,"position":1},{"key":"imaging","label":"X-Rays","icon":"Scan","visible":true,"position":2},{"key":"perio-chart","label":"Perio Chart","icon":"BarChart3","visible":true,"position":3}]},{"label":"Claims","position":3,"tabs":[{"key":"claims","label":"Claims","icon":"Receipt","visible":true,"position":0},{"key":"claim-submissions","label":"Submissions","icon":"Send","visible":true,"position":1},{"key":"claim-denials","label":"Denials","icon":"XCircle","visible":true,"position":2},{"key":"era-remittance","label":"ERA / Remittance","icon":"FileCheck","visible":true,"position":3}]},{"label":"General","position":4,"tabs":[{"key":"documents","label":"Documents","icon":"FileText","visible":true,"position":0},{"key":"education","label":"Education","icon":"GraduationCap","visible":true,"position":1},{"key":"messaging","label":"Messaging","icon":"MessageSquare","visible":true,"position":2}]},{"label":"Financial","position":5,"tabs":[{"key":"billing","label":"Billing","icon":"CreditCard","visible":true,"position":0},{"key":"payments","label":"Payments","icon":"DollarSign","visible":true,"position":1},{"key":"statements","label":"Statements","icon":"FileText","visible":true,"position":2}]}]'
WHERE code = 'general-dentistry';

-- Update physical-therapy
UPDATE practice_type SET default_tab_config = '[{"label":"Overview","position":0,"tabs":[{"key":"demographics","label":"Demographics","icon":"User","visible":true,"position":0},{"key":"insurance","label":"Insurance","icon":"Shield","visible":true,"position":1},{"key":"vitals","label":"Vitals","icon":"Activity","visible":true,"position":2},{"key":"allergies","label":"Allergies","icon":"AlertTriangle","visible":true,"position":3}]},{"label":"Encounters","position":1,"tabs":[{"key":"encounters","label":"Encounters","icon":"Calendar","visible":true,"position":0},{"key":"appointments","label":"Appointments","icon":"Clock","visible":true,"position":1},{"key":"visit-notes","label":"Visit Notes","icon":"FileText","visible":true,"position":2},{"key":"referrals","label":"Referrals","icon":"Share2","visible":true,"position":3}]},{"label":"Clinical","position":2,"tabs":[{"key":"evaluations","label":"Evaluations","icon":"ClipboardCheck","visible":true,"position":0},{"key":"treatment-plans","label":"Treatment Plans","icon":"Target","visible":true,"position":1},{"key":"exercise-log","label":"Exercise Log","icon":"Dumbbell","visible":true,"position":2},{"key":"progress-notes","label":"Progress Notes","icon":"FileText","visible":true,"position":3},{"key":"goals","label":"Goals","icon":"Target","visible":true,"position":4}]},{"label":"Claims","position":3,"tabs":[{"key":"claims","label":"Claims","icon":"Receipt","visible":true,"position":0},{"key":"claim-submissions","label":"Submissions","icon":"Send","visible":true,"position":1},{"key":"claim-denials","label":"Denials","icon":"XCircle","visible":true,"position":2},{"key":"authorization","label":"Authorization","icon":"ShieldCheck","visible":true,"position":3},{"key":"era-remittance","label":"ERA / Remittance","icon":"FileCheck","visible":true,"position":4}]},{"label":"General","position":4,"tabs":[{"key":"documents","label":"Documents","icon":"FileText","visible":true,"position":0},{"key":"education","label":"Education","icon":"GraduationCap","visible":true,"position":1},{"key":"messaging","label":"Messaging","icon":"MessageSquare","visible":true,"position":2}]},{"label":"Financial","position":5,"tabs":[{"key":"billing","label":"Billing","icon":"CreditCard","visible":true,"position":0},{"key":"payments","label":"Payments","icon":"DollarSign","visible":true,"position":1},{"key":"statements","label":"Statements","icon":"FileText","visible":true,"position":2}]}]'
WHERE code = 'physical-therapy';

-- Update home-health
UPDATE practice_type SET default_tab_config = '[{"label":"Overview","position":0,"tabs":[{"key":"demographics","label":"Demographics","icon":"User","visible":true,"position":0},{"key":"insurance","label":"Insurance","icon":"Shield","visible":true,"position":1},{"key":"vitals","label":"Vitals","icon":"Activity","visible":true,"position":2},{"key":"allergies","label":"Allergies","icon":"AlertTriangle","visible":true,"position":3},{"key":"care-plan","label":"Care Plan","icon":"ClipboardList","visible":true,"position":4}]},{"label":"Encounters","position":1,"tabs":[{"key":"encounters","label":"Visits","icon":"Calendar","visible":true,"position":0},{"key":"appointments","label":"Appointments","icon":"Clock","visible":true,"position":1},{"key":"visit-notes","label":"Visit Notes","icon":"FileText","visible":true,"position":2}]},{"label":"Clinical","position":2,"tabs":[{"key":"medications","label":"Medications","icon":"Pill","visible":true,"position":0},{"key":"oasis","label":"OASIS","icon":"FileCheck","visible":true,"position":1},{"key":"wound-care","label":"Wound Care","icon":"Bandage","visible":true,"position":2},{"key":"progress-notes","label":"Progress Notes","icon":"FileText","visible":true,"position":3}]},{"label":"Claims","position":3,"tabs":[{"key":"claims","label":"Claims","icon":"Receipt","visible":true,"position":0},{"key":"claim-submissions","label":"Submissions","icon":"Send","visible":true,"position":1},{"key":"claim-denials","label":"Denials","icon":"XCircle","visible":true,"position":2},{"key":"authorization","label":"Authorization","icon":"ShieldCheck","visible":true,"position":3},{"key":"era-remittance","label":"ERA / Remittance","icon":"FileCheck","visible":true,"position":4}]},{"label":"General","position":4,"tabs":[{"key":"documents","label":"Documents","icon":"FileText","visible":true,"position":0},{"key":"education","label":"Education","icon":"GraduationCap","visible":true,"position":1},{"key":"messaging","label":"Messaging","icon":"MessageSquare","visible":true,"position":2}]},{"label":"Financial","position":5,"tabs":[{"key":"billing","label":"Billing","icon":"CreditCard","visible":true,"position":0},{"key":"payments","label":"Payments","icon":"DollarSign","visible":true,"position":1},{"key":"statements","label":"Statements","icon":"FileText","visible":true,"position":2}]}]'
WHERE code = 'home-health';

-- Update hospitalist
UPDATE practice_type SET default_tab_config = '[{"label":"Overview","position":0,"tabs":[{"key":"demographics","label":"Demographics","icon":"User","visible":true,"position":0},{"key":"insurance","label":"Insurance","icon":"Shield","visible":true,"position":1},{"key":"vitals","label":"Vitals","icon":"Activity","visible":true,"position":2},{"key":"allergies","label":"Allergies","icon":"AlertTriangle","visible":true,"position":3},{"key":"problem-list","label":"Problem List","icon":"ClipboardList","visible":true,"position":4},{"key":"admission-info","label":"Admission","icon":"Building2","visible":true,"position":5}]},{"label":"Encounters","position":1,"tabs":[{"key":"encounters","label":"Encounters","icon":"Calendar","visible":true,"position":0},{"key":"appointments","label":"Appointments","icon":"Clock","visible":true,"position":1},{"key":"visit-notes","label":"Visit Notes","icon":"FileText","visible":true,"position":2}]},{"label":"Clinical","position":2,"tabs":[{"key":"medications","label":"Medications","icon":"Pill","visible":true,"position":0},{"key":"orders","label":"Orders","icon":"ClipboardList","visible":true,"position":1},{"key":"lab-results","label":"Lab Results","icon":"TestTube","visible":true,"position":2},{"key":"imaging","label":"Imaging","icon":"Scan","visible":true,"position":3},{"key":"procedures","label":"Procedures","icon":"Scissors","visible":true,"position":4}]},{"label":"Claims","position":3,"tabs":[{"key":"claims","label":"Claims","icon":"Receipt","visible":true,"position":0},{"key":"claim-submissions","label":"Submissions","icon":"Send","visible":true,"position":1},{"key":"claim-denials","label":"Denials","icon":"XCircle","visible":true,"position":2},{"key":"era-remittance","label":"ERA / Remittance","icon":"FileCheck","visible":true,"position":3}]},{"label":"General","position":4,"tabs":[{"key":"documents","label":"Documents","icon":"FileText","visible":true,"position":0},{"key":"consults","label":"Consults","icon":"Users","visible":true,"position":1},{"key":"messaging","label":"Messaging","icon":"MessageSquare","visible":true,"position":2}]},{"label":"Financial","position":5,"tabs":[{"key":"billing","label":"Billing","icon":"CreditCard","visible":true,"position":0},{"key":"payments","label":"Payments","icon":"DollarSign","visible":true,"position":1},{"key":"statements","label":"Statements","icon":"FileText","visible":true,"position":2}]}]'
WHERE code = 'hospitalist';

-- Also delete any org-specific tab_config entries so orgs pick up the new defaults
-- (only if they haven't customized; orgs that customized will keep their layout)
-- NOTE: We don't force-delete org configs. Orgs can reset via the UI.
